### ISSUE TITLE
Running examples on windows.

### ISSUE THREAD

**Issue by distantforest1** [cloudwu/lua-bgfx#12]
Hi I'm trying to run the examples on windows however I get this error:

```
D:\Code\bgfx\lua-bgfx-master>bin\lua.exe 00-helloworld.lua
bin\lua.exe: .\mathadapter.lua:3: attempt to call a table value
stack traceback:
        .\mathadapter.lua:3: in main chunk
        [C]: in function 'require'
        .\util.lua:7: in main chunk
        [C]: in function 'require'
        00-helloworld.lua:5: in main chunk
        [C]: in ?
```
The downloaded files are in the bin folder. What can I do here?

**Comment by cloudwu** [comment]
The pre-compiled files are expired. (I changed the math adapter APIs)

Try the updated binary files : https://github.com/cloudwu/lua-bgfx/releases/download/v0.3/lua-bgfx-0.3.zip

**Comment by distantforest1** [comment]
great! that worked
