### ISSUE TITLE
四元数求共轭w分量不应该加负号

### ISSUE THREAD

**Issue by jxo** [cloudwu/lua-bgfx#2]

**Comment by cloudwu** [comment]
这个数学库一开始只是为了重现 bgfx 的 examples, 数学库本身和 bgfx 无关。我在项目另外实现了一套数学库，过一段时间开源。

**Comment by jxo** [comment]
期待，LUA一直没找到一个合适量级的数学库。

**Comment by cloudwu** [comment]
数学库已经迁移完毕，接下来还需要做一些改进。
