### ISSUE TITLE
Bug.初始化宕机

### ISSUE THREAD

**Issue by lishaoliang** [cloudwu/lua-bgfx#4]
文件luabgfx.c，line 372.  需要初始化变量 init。否则 在lua中使用不带变量初始化 bgfx.init() 会直接宕掉。
```
bgfx_init_t init;
bgfx_init_ctor(&init);  // <= 初始化 init

init.type = BGFX_RENDERER_TYPE_COUNT;
```

**Comment by cloudwu** [comment]
ctor 只是用来填写 init 结构，和自己填是一样的。
请确认是 init 结构中哪一项没有初始化。

**Comment by lishaoliang** [comment]
bgfx.init()未填写任何参数。使用简易的测试场景。测试demo
https://github.com/lishaoliang/kltest/blob/master/lua/test/bgfx/t_bgfx.lua

测试例子：.\wlua.exe .\lua\test\bgfx\t_bgfx.lua。
github上提交的wlua.exe是修正之后

**Comment by cloudwu** [comment]
周末没环境测试，麻烦看一下最新提交。我猜测是最近版本的  `platformData` 子结构在不传参数时未初始化。
