### ISSUE TITLE
lcreateProgram在获取fs后没有检查下一个参数

### ISSUE THREAD

**Issue by KUNAGISA** [cloudwu/lua-bgfx#5]
https://github.com/cloudwu/lua-bgfx/blob/e275cbd3b2721655f24e3e825f189a59b4ddc489/luabgfx.c#L1078

为什么在bgfx的API上vs+fs的重载第三个参数只有在fs是nil的时候才检查呢？

**Comment by cloudwu** [comment]
可能是在 https://github.com/cloudwu/lua-bgfx/commit/6de3057aaad874d6e6cb5e6a877f4473e8d66614 这次提交时引入的 bug 。
