### ISSUE TITLE
winSetNextWindowSize 中 x 和 y 参数用 number 检查也比较方便些

### ISSUE THREAD

**Issue by ylme** [cloudwu/lua-bgfx#9]
https://github.com/cloudwu/lua-bgfx/blob/7edbe991fb7e1247943f82d3a5bcc64f07c5ebc7/luabgfximgui.cpp#L1546

实际使用时会传入 number 。

**Comment by cloudwu** [comment]
我另外基于 imgui 最新的 docking 分支，为 bgfx 封装了一个版本（没有使用 bgfx 拷贝的版本，和 bgfx 做的 binding ）。

那边我之前就都改过来了，并增加了很多 api ，有些这里的不兼容。所以一直没有同步。不过那个仓库暂时还是私有的。
